headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\15337\\Desktop\\aidc-fluororesin-monitor\\website"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Static site — no build required'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=86400, immutable"

[[redirects]]
from = "/"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/cn"
to = "/cn/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/jp"
to = "/jp/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]